### ISSUE TITLE
Bugs out during boss fights

### ISSUE THREAD

**Issue by potehtooo** [Lapig/PigPSO2Cam_NA#2]
Hihi! So I came across this tool as I had a habit of playing on much higher FoV while playing other MMOs before, and this has worked great so far, and it still does but I noticed that it only seems to work in fields and kinda anywhere that isn't a boss-specific fight arena, when doing urgent quests and etc. where players are teleported to a stage where it's only the boss, any changes made to the FoV is reverted

Other than that, this is kinda unrelated, but I was also wondering what exactly the Zoom slider does.

**Comment by Lapig** [comment]
I am aware of this, SEGA has like 40 something different camera tracks each with their own settings so it's either slam the changes into every single one and potentially have random broken areas that I don't have any real way to test or the current scenario of just changing primary camera track.

Zoom is for adjusting the max zoom out distance

**Comment by potehtooo** [comment]
Ahh, that's alright then, sorry if it came off as rude or demanding bringing up the issue, since it seems like a pretty obscure tool to have/use but I guess it's mostly just QoL. Well if there are any plans or anything in the works in the foreseeable future, it'll be a pleasure looking forward to it! In the meantime, I'll just appreciate having a means of changing the in-game FOV in any way at all, thanks for the time and effort you've put into creating this tool!! It really makes the game experience a lot better outside of boss fights/arenas. Cheers! c:
