### ISSUE TITLE
pso2 NGS compatible? setbgm feature from JP version?

### ISSUE THREAD

**Issue by sorasin** [Lapig/PigPSO2Cam_NA#6]
will this work in pso2 new genesis NA version, if not do you have any plans to make it compatible with the new update?

also do you plan on adding the play bgm feature from the JP version? would be very cool 

ty sorry if this has been asked before

**Comment by Lapig** [comment]
Everything is very much compatible with NGS but Sega NA has apparently gone out of their way to stop me from ever being able to play on their servers again so for the time being it is not a very high priority

![pso20210618_003936_003](https://user-images.githubusercontent.com/23328765/122507280-e9a3bf00-cfcd-11eb-8a32-9eb4b5c67af3.jpg)
